In [119]:
import pandas as pd
import numpy as np
import math
import plotly.express as px

In [120]:
episodes = pd.read_parquet("../data/logs/depth_1_onehot/eval_001/depth_1/episodes.parquet")
display(episodes.head())

,episode_id,model_version,scramble_depth,scramble_sequence,start_state,solved,total_steps,total_reward,timeout,termination_reason,moves_taken,moves_taken_count,seed,timestamp
0,eval_001-depth1-episode0,depth_1_onehot,1,R',YYBYYBYYBOOOOOOOOOGGYGGYGGYWWGWWGWWGRRRRRRRRRW...,True,3,97.0,False,solved,R' R' R',3,10042,2026-06-26T11:38:37.055582+00:00
1,eval_001-depth1-episode1,depth_1_onehot,1,F',YYYYYYOOOWOOWOOWOOGGGGGGGGGRRRWWWWWWRRYRRYRRYB...,True,1,99.0,False,solved,F,1,10043,2026-06-26T11:38:37.138089+00:00
2,eval_001-depth1-episode2,depth_1_onehot,1,U,YYYYYYYYYBBBOOOOOOOOOGGGGGGWWWWWWWWWGGGRRRRRRR...,True,3,97.0,False,solved,U U U,3,10044,2026-06-26T11:38:37.139998+00:00
3,eval_001-depth1-episode3,depth_1_onehot,1,L,BYYBYYBYYOOOOOOOOOYGGYGGYGGGWWGWWGWWRRRRRRRRRB...,False,50,-60.0,True,max_steps_reached,D' D' D' D' D' D' D' D' D' D' D' D' D' D' D' D...,50,10045,2026-06-26T11:38:37.143846+00:00
4,eval_001-depth1-episode4,depth_1_onehot,1,L',GYYGYYGYYOOOOOOOOOWGGWGGWGGBWWBWWBWWRRRRRRRRRB...,False,50,-60.0,True,max_steps_reached,D' D' D' D' D' D' D' D' D' D' D' D' D' D' D' D...,50,10046,2026-06-26T11:38:37.205747+00:00

In [121]:
solved = episodes[episodes['solved'] == True]

display(solved.head())

print(solved['start_state'].value_counts())

,episode_id,model_version,scramble_depth,scramble_sequence,start_state,solved,total_steps,total_reward,timeout,termination_reason,moves_taken,moves_taken_count,seed,timestamp
0,eval_001-depth1-episode0,depth_1_onehot,1,R',YYBYYBYYBOOOOOOOOOGGYGGYGGYWWGWWGWWGRRRRRRRRRW...,True,3,97.0,False,solved,R' R' R',3,10042,2026-06-26T11:38:37.055582+00:00
1,eval_001-depth1-episode1,depth_1_onehot,1,F',YYYYYYOOOWOOWOOWOOGGGGGGGGGRRRWWWWWWRRYRRYRRYB...,True,1,99.0,False,solved,F,1,10043,2026-06-26T11:38:37.138089+00:00
2,eval_001-depth1-episode2,depth_1_onehot,1,U,YYYYYYYYYBBBOOOOOOOOOGGGGGGWWWWWWWWWGGGRRRRRRR...,True,3,97.0,False,solved,U U U,3,10044,2026-06-26T11:38:37.139998+00:00
5,eval_001-depth1-episode5,depth_1_onehot,1,D,YYYYYYYYYOOOOOOGGGGGGGGGRRRWWWWWWWWWRRRRRRBBBB...,True,1,99.0,False,solved,D',1,10047,2026-06-26T11:38:37.268556+00:00
6,eval_001-depth1-episode6,depth_1_onehot,1,B,OOOYYYYYYOOWOOWOOWGGGGGGGGGWWWWWWRRRYRRYRRYRRB...,True,3,97.0,False,solved,B B B,3,10048,2026-06-26T11:38:37.270212+00:00

start_state
YYYYYYYYYBBBOOOOOOOOOGGGGGGWWWWWWWWWGGGRRRRRRRRRBBBBBB    11
YYYYYYYYYGGGOOOOOORRRGGGGGGWWWWWWWWWBBBRRRRRROOOBBBBBB    10
OOOYYYYYYOOWOOWOOWGGGGGGGGGWWWWWWRRRYRRYRRYRRBBBBBBBBB     9
YYYYYYYYYOOOOOOGGGGGGGGGRRRWWWWWWWWWRRRRRRBBBBBBBBBOOO     8
RRRYYYYYYOOYOOYOOYGGGGGGGGGWWWWWWOOOWRRWRRWRRBBBBBBBBB     8
YYGYYGYYGOOOOOOOOOGGWGGWGGWWWBWWBWWBRRRRRRRRRYBBYBBYBB     8
YYYYYYOOOWOOWOOWOOGGGGGGGGGRRRWWWWWWRRYRRYRRYBBBBBBBBB     7
YYYYYYYYYOOOOOOBBBGGGGGGOOOWWWWWWWWWRRRRRRGGGBBBBBBRRR     7
YYBYYBYYBOOOOOOOOOGGYGGYGGYWWGWWGWWGRRRRRRRRRWBBWBBWBB     5
YYYYYYRRRYOOYOOYOOGGGGGGGGGOOOWWWWWWRRWRRWRRWBBBBBBBBB     4
Name: count, dtype: int64

In [122]:
episodes = pd.read_parquet("../data/logs/depth_1_onehot/eval_001/depth_2/episodes.parquet")
display(display(episodes.head()))

,episode_id,model_version,scramble_depth,scramble_sequence,start_state,solved,total_steps,total_reward,timeout,termination_reason,moves_taken,moves_taken_count,seed,timestamp
0,eval_001-depth2-episode0,depth_1_onehot,2,L U',YYYYYYBBBYGGOOOOOORRRYGGYGGGWWGWWGWWBBWRRRRRRO...,False,50,-60.0,True,max_steps_reached,D' D' D' D' D' D' D' D' D' D' D' D' D' D' D' D...,50,20042,2026-06-25T16:30:19.275383+00:00
1,eval_001-depth2-episode1,depth_1_onehot,2,U B',RRGYYYYYYBBYOOYOOYOOOGGGGGGWWWWWWOOBWGGWRRWRRR...,False,50,-60.0,True,max_steps_reached,D' D' D' D' D' D' D' D' D' D' D' D' D' D' D' D...,50,20043,2026-06-25T16:30:19.312062+00:00
2,eval_001-depth2-episode2,depth_1_onehot,2,R L,BYGBYGBYGOOOOOOOOOYGWYGWYGWGWBGWBGWBRRRRRRRRRY...,False,50,-60.0,True,max_steps_reached,D' D' D' D' D' D' D' D' D' D' D' D' D' D' D' D...,50,20044,2026-06-25T16:30:19.343833+00:00
3,eval_001-depth2-episode3,depth_1_onehot,2,B' D,RRRYYYYYYOOYOOYGGGGGGGGGWRROWWOWWOWWWRRWRRBBBB...,False,50,-60.0,True,max_steps_reached,D' D' D' D' D' D' D' D' D' D' D' D' D' D' D' D...,50,20045,2026-06-25T16:30:19.374307+00:00
4,eval_001-depth2-episode4,depth_1_onehot,2,D D,YYYYYYYYYOOOOOORRRGGGGGGBBBWWWWWWWWWRRRRRROOOB...,True,2,98.0,False,solved,D' D',2,20046,2026-06-25T16:30:19.407217+00:00

None

In [123]:
episodes = pd.read_parquet("../data/logs/depth_1_onehot/eval_001/depth_2/episodes.parquet")
display(episodes.head())

,episode_id,model_version,scramble_depth,scramble_sequence,start_state,solved,total_steps,total_reward,timeout,termination_reason,moves_taken,moves_taken_count,seed,timestamp
0,eval_001-depth2-episode0,depth_1_onehot,2,L U',YYYYYYBBBYGGOOOOOORRRYGGYGGGWWGWWGWWBBWRRRRRRO...,False,50,-60.0,True,max_steps_reached,D' D' D' D' D' D' D' D' D' D' D' D' D' D' D' D...,50,20042,2026-06-25T16:30:19.275383+00:00
1,eval_001-depth2-episode1,depth_1_onehot,2,U B',RRGYYYYYYBBYOOYOOYOOOGGGGGGWWWWWWOOBWGGWRRWRRR...,False,50,-60.0,True,max_steps_reached,D' D' D' D' D' D' D' D' D' D' D' D' D' D' D' D...,50,20043,2026-06-25T16:30:19.312062+00:00
2,eval_001-depth2-episode2,depth_1_onehot,2,R L,BYGBYGBYGOOOOOOOOOYGWYGWYGWGWBGWBGWBRRRRRRRRRY...,False,50,-60.0,True,max_steps_reached,D' D' D' D' D' D' D' D' D' D' D' D' D' D' D' D...,50,20044,2026-06-25T16:30:19.343833+00:00
3,eval_001-depth2-episode3,depth_1_onehot,2,B' D,RRRYYYYYYOOYOOYGGGGGGGGGWRROWWOWWOWWWRRWRRBBBB...,False,50,-60.0,True,max_steps_reached,D' D' D' D' D' D' D' D' D' D' D' D' D' D' D' D...,50,20045,2026-06-25T16:30:19.374307+00:00
4,eval_001-depth2-episode4,depth_1_onehot,2,D D,YYYYYYYYYOOOOOORRRGGGGGGBBBWWWWWWWWWRRRRRROOOB...,True,2,98.0,False,solved,D' D',2,20046,2026-06-25T16:30:19.407217+00:00

In [124]:
solved = episodes[episodes['solved'] == True]

display(solved.head())

print(solved['total_steps'].value_counts())

,episode_id,model_version,scramble_depth,scramble_sequence,start_state,solved,total_steps,total_reward,timeout,termination_reason,moves_taken,moves_taken_count,seed,timestamp
4,eval_001-depth2-episode4,depth_1_onehot,2,D D,YYYYYYYYYOOOOOORRRGGGGGGBBBWWWWWWWWWRRRRRROOOB...,True,2,98.0,False,solved,D' D',2,20046,2026-06-25T16:30:19.407217+00:00
6,eval_001-depth2-episode6,depth_1_onehot,2,R D,YYGYYGYYGOOOOOOGGWGGWGGWRRRWWWWWWBBBRRRRRRYBBY...,True,4,96.0,False,solved,D' R R R,4,20048,2026-06-25T16:30:19.444992+00:00
22,eval_001-depth2-episode22,depth_1_onehot,2,D D,YYYYYYYYYOOOOOORRRGGGGGGBBBWWWWWWWWWRRRRRROOOB...,True,2,98.0,False,solved,D' D',2,20064,2026-06-25T16:30:19.988547+00:00
23,eval_001-depth2-episode23,depth_1_onehot,2,R D',YYGYYGYYGOOOOOOYBBGGWGGWOOOBBBWWWWWWRRRRRRGGWY...,True,6,94.0,False,solved,D' D' D' R R R,6,20065,2026-06-25T16:30:19.990637+00:00
62,eval_001-depth2-episode62,depth_1_onehot,2,R R,YYWYYWYYWOOOOOOOOOGGBGGBGGBWWYWWYWWYRRRRRRRRRG...,True,2,98.0,False,solved,R R,2,20104,2026-06-25T16:30:21.386091+00:00

total_steps
2    3
4    2
6    2
Name: count, dtype: int64

In [125]:
episodes = pd.read_parquet("../data/logs/depth_1_onehot/eval_001/depth_1/episodes.parquet")
display(episodes.head())

,episode_id,model_version,scramble_depth,scramble_sequence,start_state,solved,total_steps,total_reward,timeout,termination_reason,moves_taken,moves_taken_count,seed,timestamp
0,eval_001-depth1-episode0,depth_1_onehot,1,R',YYBYYBYYBOOOOOOOOOGGYGGYGGYWWGWWGWWGRRRRRRRRRW...,True,3,97.0,False,solved,R' R' R',3,10042,2026-06-26T11:38:37.055582+00:00
1,eval_001-depth1-episode1,depth_1_onehot,1,F',YYYYYYOOOWOOWOOWOOGGGGGGGGGRRRWWWWWWRRYRRYRRYB...,True,1,99.0,False,solved,F,1,10043,2026-06-26T11:38:37.138089+00:00
2,eval_001-depth1-episode2,depth_1_onehot,1,U,YYYYYYYYYBBBOOOOOOOOOGGGGGGWWWWWWWWWGGGRRRRRRR...,True,3,97.0,False,solved,U U U,3,10044,2026-06-26T11:38:37.139998+00:00
3,eval_001-depth1-episode3,depth_1_onehot,1,L,BYYBYYBYYOOOOOOOOOYGGYGGYGGGWWGWWGWWRRRRRRRRRB...,False,50,-60.0,True,max_steps_reached,D' D' D' D' D' D' D' D' D' D' D' D' D' D' D' D...,50,10045,2026-06-26T11:38:37.143846+00:00
4,eval_001-depth1-episode4,depth_1_onehot,1,L',GYYGYYGYYOOOOOOOOOWGGWGGWGGBWWBWWBWWRRRRRRRRRB...,False,50,-60.0,True,max_steps_reached,D' D' D' D' D' D' D' D' D' D' D' D' D' D' D' D...,50,10046,2026-06-26T11:38:37.205747+00:00

In [126]:
solved = episodes[episodes['solved'] == True]

display(solved.head())

print(solved['start_state'].value_counts())

,episode_id,model_version,scramble_depth,scramble_sequence,start_state,solved,total_steps,total_reward,timeout,termination_reason,moves_taken,moves_taken_count,seed,timestamp
0,eval_001-depth1-episode0,depth_1_onehot,1,R',YYBYYBYYBOOOOOOOOOGGYGGYGGYWWGWWGWWGRRRRRRRRRW...,True,3,97.0,False,solved,R' R' R',3,10042,2026-06-26T11:38:37.055582+00:00
1,eval_001-depth1-episode1,depth_1_onehot,1,F',YYYYYYOOOWOOWOOWOOGGGGGGGGGRRRWWWWWWRRYRRYRRYB...,True,1,99.0,False,solved,F,1,10043,2026-06-26T11:38:37.138089+00:00
2,eval_001-depth1-episode2,depth_1_onehot,1,U,YYYYYYYYYBBBOOOOOOOOOGGGGGGWWWWWWWWWGGGRRRRRRR...,True,3,97.0,False,solved,U U U,3,10044,2026-06-26T11:38:37.139998+00:00
5,eval_001-depth1-episode5,depth_1_onehot,1,D,YYYYYYYYYOOOOOOGGGGGGGGGRRRWWWWWWWWWRRRRRRBBBB...,True,1,99.0,False,solved,D',1,10047,2026-06-26T11:38:37.268556+00:00
6,eval_001-depth1-episode6,depth_1_onehot,1,B,OOOYYYYYYOOWOOWOOWGGGGGGGGGWWWWWWRRRYRRYRRYRRB...,True,3,97.0,False,solved,B B B,3,10048,2026-06-26T11:38:37.270212+00:00

start_state
YYYYYYYYYBBBOOOOOOOOOGGGGGGWWWWWWWWWGGGRRRRRRRRRBBBBBB    11
YYYYYYYYYGGGOOOOOORRRGGGGGGWWWWWWWWWBBBRRRRRROOOBBBBBB    10
OOOYYYYYYOOWOOWOOWGGGGGGGGGWWWWWWRRRYRRYRRYRRBBBBBBBBB     9
YYYYYYYYYOOOOOOGGGGGGGGGRRRWWWWWWWWWRRRRRRBBBBBBBBBOOO     8
RRRYYYYYYOOYOOYOOYGGGGGGGGGWWWWWWOOOWRRWRRWRRBBBBBBBBB     8
YYGYYGYYGOOOOOOOOOGGWGGWGGWWWBWWBWWBRRRRRRRRRYBBYBBYBB     8
YYYYYYOOOWOOWOOWOOGGGGGGGGGRRRWWWWWWRRYRRYRRYBBBBBBBBB     7
YYYYYYYYYOOOOOOBBBGGGGGGOOOWWWWWWWWWRRRRRRGGGBBBBBBRRR     7
YYBYYBYYBOOOOOOOOOGGYGGYGGYWWGWWGWWGRRRRRRRRRWBBWBBWBB     5
YYYYYYRRRYOOYOOYOOGGGGGGGGGOOOWWWWWWRRWRRWRRWBBBBBBBBB     4
Name: count, dtype: int64

In [127]:
df = pd.read_parquet("../data/processed/training/parquet/depth_1.parquet")
print(df["scramble_moves"].value_counts())

scramble_moves
D     1
U     1
F     1
L     1
D'    1
F'    1
L'    1
R'    1
R     1
U'    1
B'    1
B     1
Name: count, dtype: int64

In [128]:
episodes = pd.read_parquet("../data/logs/depth_1_onehot_2000/eval_001/depth_1/episodes.parquet")
display(episodes.head())

,episode_id,model_version,scramble_depth,scramble_sequence,start_state,solved,total_steps,total_reward,timeout,termination_reason,moves_taken,moves_taken_count,seed,timestamp
0,eval_001-depth1-episode0,depth_1_onehot_2000,1,D,YYYYYYYYYOOOOOOGGGGGGGGGRRRWWWWWWWWWRRRRRRBBBB...,True,1,99.0,False,solved,D',1,None,2026-06-29T13:41:59.352069+00:00
1,eval_001-depth1-episode1,depth_1_onehot_2000,1,U,YYYYYYYYYBBBOOOOOOOOOGGGGGGWWWWWWWWWGGGRRRRRRR...,True,3,97.0,False,solved,U U U,3,None,2026-06-29T13:41:59.408367+00:00
2,eval_001-depth1-episode2,depth_1_onehot_2000,1,F,YYYYYYRRRYOOYOOYOOGGGGGGGGGOOOWWWWWWRRWRRWRRWB...,True,3,97.0,False,solved,F F F,3,None,2026-06-29T13:41:59.411201+00:00
3,eval_001-depth1-episode3,depth_1_onehot_2000,1,L,BYYBYYBYYOOOOOOOOOYGGYGGYGGGWWGWWGWWRRRRRRRRRB...,False,50,-60.0,True,max_steps_reached,B F F F F F F F F F F F F F F F F F F F F F F ...,50,None,2026-06-29T13:41:59.413552+00:00
4,eval_001-depth1-episode4,depth_1_onehot_2000,1,D',YYYYYYYYYOOOOOOBBBGGGGGGOOOWWWWWWWWWRRRRRRGGGB...,True,3,97.0,False,solved,D' D' D',3,None,2026-06-29T13:41:59.453776+00:00

In [129]:
solved = episodes[episodes['solved'] == True]

display(solved.head())

print(solved['start_state'].value_counts())

,episode_id,model_version,scramble_depth,scramble_sequence,start_state,solved,total_steps,total_reward,timeout,termination_reason,moves_taken,moves_taken_count,seed,timestamp
0,eval_001-depth1-episode0,depth_1_onehot_2000,1,D,YYYYYYYYYOOOOOOGGGGGGGGGRRRWWWWWWWWWRRRRRRBBBB...,True,1,99.0,False,solved,D',1,None,2026-06-29T13:41:59.352069+00:00
1,eval_001-depth1-episode1,depth_1_onehot_2000,1,U,YYYYYYYYYBBBOOOOOOOOOGGGGGGWWWWWWWWWGGGRRRRRRR...,True,3,97.0,False,solved,U U U,3,None,2026-06-29T13:41:59.408367+00:00
2,eval_001-depth1-episode2,depth_1_onehot_2000,1,F,YYYYYYRRRYOOYOOYOOGGGGGGGGGOOOWWWWWWRRWRRWRRWB...,True,3,97.0,False,solved,F F F,3,None,2026-06-29T13:41:59.411201+00:00
4,eval_001-depth1-episode4,depth_1_onehot_2000,1,D',YYYYYYYYYOOOOOOBBBGGGGGGOOOWWWWWWWWWRRRRRRGGGB...,True,3,97.0,False,solved,D' D' D',3,None,2026-06-29T13:41:59.453776+00:00
5,eval_001-depth1-episode5,depth_1_onehot_2000,1,F',YYYYYYOOOWOOWOOWOOGGGGGGGGGRRRWWWWWWRRYRRYRRYB...,True,1,99.0,False,solved,F,1,None,2026-06-29T13:41:59.456860+00:00

start_state
YYYYYYYYYOOOOOOGGGGGGGGGRRRWWWWWWWWWRRRRRRBBBBBBBBBOOO    9
YYYYYYYYYBBBOOOOOOOOOGGGGGGWWWWWWWWWGGGRRRRRRRRRBBBBBB    9
YYYYYYRRRYOOYOOYOOGGGGGGGGGOOOWWWWWWRRWRRWRRWBBBBBBBBB    9
YYYYYYYYYOOOOOOBBBGGGGGGOOOWWWWWWWWWRRRRRRGGGBBBBBBRRR    8
YYYYYYOOOWOOWOOWOOGGGGGGGGGRRRWWWWWWRRYRRYRRYBBBBBBBBB    8
YYBYYBYYBOOOOOOOOOGGYGGYGGYWWGWWGWWGRRRRRRRRRWBBWBBWBB    8
YYGYYGYYGOOOOOOOOOGGWGGWGGWWWBWWBWWBRRRRRRRRRYBBYBBYBB    8
YYYYYYYYYGGGOOOOOORRRGGGGGGWWWWWWWWWBBBRRRRRROOOBBBBBB    8
RRRYYYYYYOOYOOYOOYGGGGGGGGGWWWWWWOOOWRRWRRWRRBBBBBBBBB    8
OOOYYYYYYOOWOOWOOWGGGGGGGGGWWWWWWRRRYRRYRRYRRBBBBBBBBB    8
Name: count, dtype: int64

In [130]:
history = pd.read_csv("../models/artifacts/ppo/depth_1_2_onehot/v001/history.csv")

display(history.head())
print(history.shape)

,approx_kl,clip_fraction,entropy,explained_variance,loss,mean_episode_length,mean_episode_reward,policy_loss,timesteps,train_solve_rate,value_loss,evaluation
0,0.004274,0.025586,2.481479,-0.057582,-0.040789,9.57,-0.1772,-0.021377,2048,0.05,0.010806,NaN
1,0.005242,0.056885,2.475433,0.020987,-0.048012,9.06,-0.1086,-0.030735,4096,0.11,0.014955,NaN
2,0.007213,0.081982,2.462716,0.062328,-0.051469,9.16,-0.1161,-0.035497,6144,0.10,0.017311,NaN
3,0.009122,0.137402,2.444471,-0.022117,-0.057795,9.39,-0.1524,-0.042527,8192,0.07,0.018354,NaN
4,0.011967,0.192188,2.412887,0.132290,-0.059176,9.29,-0.1319,-0.047032,10240,0.09,0.023969,"{""by_depth"":{""1"":{""action_counts"":{""B"":1,""B'"":..."

(489, 12)

In [131]:
fig1 = px.bar(history, x='timesteps', y='mean_episode_reward')
fig1.show()

In [132]:
history = pd.read_csv("../models/artifacts/ppo/depth_1_onehot/v009/history.csv")

display(history.head())
print(history.shape)

fig1 = px.bar(history, x='timesteps', y='train_solve_rate')
fig1.show()

,approx_kl,clip_fraction,entropy,explained_variance,loss,mean_episode_length,mean_episode_reward,policy_loss,timesteps,train_solve_rate,value_loss,evaluation
0,0.002966,0.021094,2.480210,-0.025382,-0.037252,4.80,-0.1060,-0.026141,2048,0.05,0.027382,NaN
1,0.008856,0.118555,2.464976,0.019126,-0.047871,4.42,0.0208,-0.040258,4096,0.16,0.034075,NaN
2,0.018618,0.251221,2.400262,0.043592,-0.054333,4.30,0.0655,-0.056089,6144,0.20,0.051517,NaN
3,0.023883,0.371143,2.273853,0.128468,-0.053463,3.78,0.2192,-0.084891,8192,0.34,0.108332,NaN
4,0.025069,0.460791,2.098712,0.232203,-0.056918,3.16,0.4034,-0.106189,10240,0.50,0.140518,"{""by_depth"":{""1"":{""action_counts"":{""B"":1,""B'"":..."

(489, 12)

In [133]:
history = pd.read_csv("../models/artifacts/ppo/depth_1_3_onehot/v001/history.csv")

display(history.head())
print(history.shape)

fig1 = px.bar(history, x='timesteps', y='train_solve_rate')
fig1.show()

,timesteps,policy_loss,value_loss,entropy,approx_kl,clip_fraction,loss,explained_variance,mean_episode_reward,mean_episode_length,train_solve_rate,timeout_rate,inverse_move_rate,evaluation
0,2048,-0.027216,0.003837,2.481435,0.003694,0.025146,-0.050111,-0.187237,-0.3589,19.64,0.02,0.98,0.086049,NaN
1,4096,-0.060968,0.001468,2.471692,0.008021,0.118506,-0.084951,0.040781,-0.3765,20.00,0.00,1.00,0.076500,NaN
2,6144,-0.046633,0.004367,2.460479,0.007292,0.100293,-0.069055,0.179114,-0.3348,19.43,0.03,0.97,0.075656,NaN
3,8192,-0.048295,0.005037,2.445252,0.008451,0.119873,-0.070229,0.079202,-0.3437,19.47,0.03,0.97,0.084232,NaN
4,10240,-0.055671,0.004503,2.431901,0.009390,0.152148,-0.077738,0.070343,-0.3156,19.06,0.05,0.95,0.083945,"{""by_depth"":{""1"":{""action_counts"":{""B"":0,""B'"":..."

(245, 14)

In [134]:
episodes = pd.read_parquet("../data/logs/depth_1_3_v1/eval_001/depth_1/episodes.parquet")
display(episodes.head())


solved = episodes[episodes['solved'] == True]

display(solved.head())

print(solved['start_state'].value_counts())
print(solved['scramble_depth'].value_counts())

,episode_id,model_version,scramble_depth,scramble_sequence,start_state,solved,total_steps,total_reward,timeout,termination_reason,moves_taken,moves_taken_count,seed,timestamp
0,eval_001-depth1-episode0,depth_1_3_v1,1,D,YYYYYYYYYOOOOOOGGGGGGGGGRRRWWWWWWWWWRRRRRRBBBB...,True,1,0.99,False,solved,D',1,None,2026-07-01T11:38:27.477115+00:00
1,eval_001-depth1-episode1,depth_1_3_v1,1,U,YYYYYYYYYBBBOOOOOOOOOGGGGGGWWWWWWWWWGGGRRRRRRR...,True,3,0.97,False,solved,U U U,3,None,2026-07-01T11:38:27.560329+00:00
2,eval_001-depth1-episode2,depth_1_3_v1,1,F,YYYYYYRRRYOOYOOYOOGGGGGGGGGOOOWWWWWWRRWRRWRRWB...,True,1,0.99,False,solved,F',1,None,2026-07-01T11:38:27.564453+00:00
3,eval_001-depth1-episode3,depth_1_3_v1,1,L,BYYBYYBYYOOOOOOOOOYGGYGGYGGGWWGWWGWWRRRRRRRRRB...,True,1,0.99,False,solved,L',1,None,2026-07-01T11:38:27.566193+00:00
4,eval_001-depth1-episode4,depth_1_3_v1,1,D',YYYYYYYYYOOOOOOBBBGGGGGGOOOWWWWWWWWWRRRRRRGGGB...,True,1,0.99,False,solved,D,1,None,2026-07-01T11:38:27.567712+00:00

,episode_id,model_version,scramble_depth,scramble_sequence,start_state,solved,total_steps,total_reward,timeout,termination_reason,moves_taken,moves_taken_count,seed,timestamp
0,eval_001-depth1-episode0,depth_1_3_v1,1,D,YYYYYYYYYOOOOOOGGGGGGGGGRRRWWWWWWWWWRRRRRRBBBB...,True,1,0.99,False,solved,D',1,None,2026-07-01T11:38:27.477115+00:00
1,eval_001-depth1-episode1,depth_1_3_v1,1,U,YYYYYYYYYBBBOOOOOOOOOGGGGGGWWWWWWWWWGGGRRRRRRR...,True,3,0.97,False,solved,U U U,3,None,2026-07-01T11:38:27.560329+00:00
2,eval_001-depth1-episode2,depth_1_3_v1,1,F,YYYYYYRRRYOOYOOYOOGGGGGGGGGOOOWWWWWWRRWRRWRRWB...,True,1,0.99,False,solved,F',1,None,2026-07-01T11:38:27.564453+00:00
3,eval_001-depth1-episode3,depth_1_3_v1,1,L,BYYBYYBYYOOOOOOOOOYGGYGGYGGGWWGWWGWWRRRRRRRRRB...,True,1,0.99,False,solved,L',1,None,2026-07-01T11:38:27.566193+00:00
4,eval_001-depth1-episode4,depth_1_3_v1,1,D',YYYYYYYYYOOOOOOBBBGGGGGGOOOWWWWWWWWWRRRRRRGGGB...,True,1,0.99,False,solved,D,1,None,2026-07-01T11:38:27.567712+00:00

start_state
YYYYYYYYYOOOOOOGGGGGGGGGRRRWWWWWWWWWRRRRRRBBBBBBBBBOOO    1
YYYYYYYYYBBBOOOOOOOOOGGGGGGWWWWWWWWWGGGRRRRRRRRRBBBBBB    1
YYYYYYRRRYOOYOOYOOGGGGGGGGGOOOWWWWWWRRWRRWRRWBBBBBBBBB    1
BYYBYYBYYOOOOOOOOOYGGYGGYGGGWWGWWGWWRRRRRRRRRBBWBBWBBW    1
YYYYYYYYYOOOOOOBBBGGGGGGOOOWWWWWWWWWRRRRRRGGGBBBBBBRRR    1
YYYYYYOOOWOOWOOWOOGGGGGGGGGRRRWWWWWWRRYRRYRRYBBBBBBBBB    1
GYYGYYGYYOOOOOOOOOWGGWGGWGGBWWBWWBWWRRRRRRRRRBBYBBYBBY    1
YYBYYBYYBOOOOOOOOOGGYGGYGGYWWGWWGWWGRRRRRRRRRWBBWBBWBB    1
YYGYYGYYGOOOOOOOOOGGWGGWGGWWWBWWBWWBRRRRRRRRRYBBYBBYBB    1
YYYYYYYYYGGGOOOOOORRRGGGGGGWWWWWWWWWBBBRRRRRROOOBBBBBB    1
RRRYYYYYYOOYOOYOOYGGGGGGGGGWWWWWWOOOWRRWRRWRRBBBBBBBBB    1
OOOYYYYYYOOWOOWOOWGGGGGGGGGWWWWWWRRRYRRYRRYRRBBBBBBBBB    1
Name: count, dtype: int64
scramble_depth
1    12
Name: count, dtype: int64

In [135]:
episodes = pd.read_parquet("../data/logs/depth_1_2_v1/eval_001/depth_2/episodes.parquet")
display(episodes.head())

print(episodes['start_state'].value_counts())
print(episodes['scramble_depth'].value_counts())


solved = episodes[episodes['solved'] == True]

display(solved.head())

print(solved['start_state'].value_counts())
print(solved['scramble_depth'].value_counts())

,episode_id,model_version,scramble_depth,scramble_sequence,start_state,solved,total_steps,total_reward,timeout,termination_reason,moves_taken,moves_taken_count,seed,timestamp
0,eval_001-depth2-episode0,depth_1_2_v1,2,F' L,BYYBYYBOOWOOWOOWOOYGGYGGOGGGRRGWWGWWRRRRRRYYYB...,True,2,0.98,False,solved,L' F,2,None,2026-07-01T12:17:00.745145+00:00
1,eval_001-depth2-episode1,depth_1_2_v1,2,L U',YYYYYYBBBYGGOOOOOORRRYGGYGGGWWGWWGWWBBWRRRRRRO...,True,2,0.98,False,solved,U L',2,None,2026-07-01T12:17:00.749505+00:00
2,eval_001-depth2-episode2,depth_1_2_v1,2,F' D',YYYYYYOOOWOOWOOBBBGGGGGGWOORWWRWWRWWRRYRRYGGGB...,True,2,0.98,False,solved,D F,2,None,2026-07-01T12:17:00.753814+00:00
3,eval_001-depth2-episode3,depth_1_2_v1,2,F' B,OOOYYYOOOWOWWOWWOWGGGGGGGGGRRRWWWRRRYRYYRYYRYB...,True,2,0.98,False,solved,F B',2,None,2026-07-01T12:17:00.757370+00:00
4,eval_001-depth2-episode4,depth_1_2_v1,2,B R',OOBYYBYYBWWWOOOOOOGGOGGYGGYWWGWWGRRGYRRYRRYRRR...,True,2,0.98,False,solved,R B',2,None,2026-07-01T12:17:00.761025+00:00

start_state
BYYBYYBOOWOOWOOWOOYGGYGGOGGGRRGWWGWWRRRRRRYYYBBWBBWBBR    1
YYYYYYBBBYGGOOOOOORRRYGGYGGGWWGWWGWWBBWRRRRRROOOBBWBBW    1
YYYYYYOOOWOOWOOBBBGGGGGGWOORWWRWWRWWRRYRRYGGGBBBBBBRRY    1
OOOYYYOOOWOWWOWWOWGGGGGGGGGRRRWWWRRRYRYYRYYRYBBBBBBBBB    1
OOBYYBYYBWWWOOOOOOGGOGGYGGYWWGWWGRRGYRRYRRYRRRBBWBBWBB    1
                                                         ..
RYYBYYBYYOOOOOOBBBYGGYGGYOOGWWGWWOWWGRRGRRGRRBBWBBWRRW    1
YYYYYYYYYBBBOOOGGGOOOGGGRRRWWWWWWWWWGGGRRRBBBRRRBBBOOO    1
YYWYYWYYWOOOOOOOOOGGBGGBGGBWWYWWYWWYRRRRRRRRRGBBGBBGBB    1
YYYYYYBRRYOOYOOYGGRGGRGGRGGGOOWWWWWWRRWRRWBBWBBBBBBOOO    1
GYYGYYGOOWOOWOOWOORGGWGGWGGBRRBWWBWWYYYRRRRRRBBOBBYBBY    1
Name: count, Length: 100, dtype: int64
scramble_depth
2    100
Name: count, dtype: int64

,episode_id,model_version,scramble_depth,scramble_sequence,start_state,solved,total_steps,total_reward,timeout,termination_reason,moves_taken,moves_taken_count,seed,timestamp
0,eval_001-depth2-episode0,depth_1_2_v1,2,F' L,BYYBYYBOOWOOWOOWOOYGGYGGOGGGRRGWWGWWRRRRRRYYYB...,True,2,0.98,False,solved,L' F,2,None,2026-07-01T12:17:00.745145+00:00
1,eval_001-depth2-episode1,depth_1_2_v1,2,L U',YYYYYYBBBYGGOOOOOORRRYGGYGGGWWGWWGWWBBWRRRRRRO...,True,2,0.98,False,solved,U L',2,None,2026-07-01T12:17:00.749505+00:00
2,eval_001-depth2-episode2,depth_1_2_v1,2,F' D',YYYYYYOOOWOOWOOBBBGGGGGGWOORWWRWWRWWRRYRRYGGGB...,True,2,0.98,False,solved,D F,2,None,2026-07-01T12:17:00.753814+00:00
3,eval_001-depth2-episode3,depth_1_2_v1,2,F' B,OOOYYYOOOWOWWOWWOWGGGGGGGGGRRRWWWRRRYRYYRYYRYB...,True,2,0.98,False,solved,F B',2,None,2026-07-01T12:17:00.757370+00:00
4,eval_001-depth2-episode4,depth_1_2_v1,2,B R',OOBYYBYYBWWWOOOOOOGGOGGYGGYWWGWWGRRGYRRYRRYRRR...,True,2,0.98,False,solved,R B',2,None,2026-07-01T12:17:00.761025+00:00

start_state
BYYBYYBOOWOOWOOWOOYGGYGGOGGGRRGWWGWWRRRRRRYYYBBWBBWBBR    1
YYYYYYBBBYGGOOOOOORRRYGGYGGGWWGWWGWWBBWRRRRRROOOBBWBBW    1
YYYYYYOOOWOOWOOBBBGGGGGGWOORWWRWWRWWRRYRRYGGGBBBBBBRRY    1
OOOYYYOOOWOWWOWWOWGGGGGGGGGRRRWWWRRRYRYYRYYRYBBBBBBBBB    1
OOBYYBYYBWWWOOOOOOGGOGGYGGYWWGWWGRRGYRRYRRYRRRBBWBBWBB    1
                                                         ..
RYYBYYBYYOOOOOOBBBYGGYGGYOOGWWGWWOWWGRRGRRGRRBBWBBWRRW    1
YYYYYYYYYBBBOOOGGGOOOGGGRRRWWWWWWWWWGGGRRRBBBRRRBBBOOO    1
YYWYYWYYWOOOOOOOOOGGBGGBGGBWWYWWYWWYRRRRRRRRRGBBGBBGBB    1
YYYYYYBRRYOOYOOYGGRGGRGGRGGGOOWWWWWWRRWRRWBBWBBBBBBOOO    1
GYYGYYGOOWOOWOOWOORGGWGGWGGBRRBWWBWWYYYRRRRRRBBOBBYBBY    1
Name: count, Length: 100, dtype: int64
scramble_depth
2    100
Name: count, dtype: int64