In [57]:
import pandas as pd
import numpy as np
import math
import plotly.express as px

In [58]:
episodes = pd.read_parquet("../data/logs/depth_1_onehot/eval_001/depth_1/episodes.parquet")
display(episodes.head())

,episode_id,model_version,scramble_depth,scramble_sequence,start_state,solved,total_steps,total_reward,timeout,termination_reason,moves_taken,moves_taken_count,seed,timestamp
0,eval_001-depth1-episode0,depth_1_onehot,1,R',YYBYYBYYBOOOOOOOOOGGYGGYGGYWWGWWGWWGRRRRRRRRRW...,True,3,97.0,False,solved,R' R' R',3,10042,2026-06-26T11:38:37.055582+00:00
1,eval_001-depth1-episode1,depth_1_onehot,1,F',YYYYYYOOOWOOWOOWOOGGGGGGGGGRRRWWWWWWRRYRRYRRYB...,True,1,99.0,False,solved,F,1,10043,2026-06-26T11:38:37.138089+00:00
2,eval_001-depth1-episode2,depth_1_onehot,1,U,YYYYYYYYYBBBOOOOOOOOOGGGGGGWWWWWWWWWGGGRRRRRRR...,True,3,97.0,False,solved,U U U,3,10044,2026-06-26T11:38:37.139998+00:00
3,eval_001-depth1-episode3,depth_1_onehot,1,L,BYYBYYBYYOOOOOOOOOYGGYGGYGGGWWGWWGWWRRRRRRRRRB...,False,50,-60.0,True,max_steps_reached,D' D' D' D' D' D' D' D' D' D' D' D' D' D' D' D...,50,10045,2026-06-26T11:38:37.143846+00:00
4,eval_001-depth1-episode4,depth_1_onehot,1,L',GYYGYYGYYOOOOOOOOOWGGWGGWGGBWWBWWBWWRRRRRRRRRB...,False,50,-60.0,True,max_steps_reached,D' D' D' D' D' D' D' D' D' D' D' D' D' D' D' D...,50,10046,2026-06-26T11:38:37.205747+00:00

In [59]:
solved = episodes[episodes['solved'] == True]

display(solved.head())

print(solved['start_state'].value_counts())

,episode_id,model_version,scramble_depth,scramble_sequence,start_state,solved,total_steps,total_reward,timeout,termination_reason,moves_taken,moves_taken_count,seed,timestamp
0,eval_001-depth1-episode0,depth_1_onehot,1,R',YYBYYBYYBOOOOOOOOOGGYGGYGGYWWGWWGWWGRRRRRRRRRW...,True,3,97.0,False,solved,R' R' R',3,10042,2026-06-26T11:38:37.055582+00:00
1,eval_001-depth1-episode1,depth_1_onehot,1,F',YYYYYYOOOWOOWOOWOOGGGGGGGGGRRRWWWWWWRRYRRYRRYB...,True,1,99.0,False,solved,F,1,10043,2026-06-26T11:38:37.138089+00:00
2,eval_001-depth1-episode2,depth_1_onehot,1,U,YYYYYYYYYBBBOOOOOOOOOGGGGGGWWWWWWWWWGGGRRRRRRR...,True,3,97.0,False,solved,U U U,3,10044,2026-06-26T11:38:37.139998+00:00
5,eval_001-depth1-episode5,depth_1_onehot,1,D,YYYYYYYYYOOOOOOGGGGGGGGGRRRWWWWWWWWWRRRRRRBBBB...,True,1,99.0,False,solved,D',1,10047,2026-06-26T11:38:37.268556+00:00
6,eval_001-depth1-episode6,depth_1_onehot,1,B,OOOYYYYYYOOWOOWOOWGGGGGGGGGWWWWWWRRRYRRYRRYRRB...,True,3,97.0,False,solved,B B B,3,10048,2026-06-26T11:38:37.270212+00:00

start_state
YYYYYYYYYBBBOOOOOOOOOGGGGGGWWWWWWWWWGGGRRRRRRRRRBBBBBB    11
YYYYYYYYYGGGOOOOOORRRGGGGGGWWWWWWWWWBBBRRRRRROOOBBBBBB    10
OOOYYYYYYOOWOOWOOWGGGGGGGGGWWWWWWRRRYRRYRRYRRBBBBBBBBB     9
YYYYYYYYYOOOOOOGGGGGGGGGRRRWWWWWWWWWRRRRRRBBBBBBBBBOOO     8
RRRYYYYYYOOYOOYOOYGGGGGGGGGWWWWWWOOOWRRWRRWRRBBBBBBBBB     8
YYGYYGYYGOOOOOOOOOGGWGGWGGWWWBWWBWWBRRRRRRRRRYBBYBBYBB     8
YYYYYYOOOWOOWOOWOOGGGGGGGGGRRRWWWWWWRRYRRYRRYBBBBBBBBB     7
YYYYYYYYYOOOOOOBBBGGGGGGOOOWWWWWWWWWRRRRRRGGGBBBBBBRRR     7
YYBYYBYYBOOOOOOOOOGGYGGYGGYWWGWWGWWGRRRRRRRRRWBBWBBWBB     5
YYYYYYRRRYOOYOOYOOGGGGGGGGGOOOWWWWWWRRWRRWRRWBBBBBBBBB     4
Name: count, dtype: int64

In [60]:
episodes = pd.read_parquet("../data/logs/depth_1_onehot/eval_001/depth_2/episodes.parquet")
display(display(episodes.head()))

,episode_id,model_version,scramble_depth,scramble_sequence,start_state,solved,total_steps,total_reward,timeout,termination_reason,moves_taken,moves_taken_count,seed,timestamp
0,eval_001-depth2-episode0,depth_1_onehot,2,L U',YYYYYYBBBYGGOOOOOORRRYGGYGGGWWGWWGWWBBWRRRRRRO...,False,50,-60.0,True,max_steps_reached,D' D' D' D' D' D' D' D' D' D' D' D' D' D' D' D...,50,20042,2026-06-25T16:30:19.275383+00:00
1,eval_001-depth2-episode1,depth_1_onehot,2,U B',RRGYYYYYYBBYOOYOOYOOOGGGGGGWWWWWWOOBWGGWRRWRRR...,False,50,-60.0,True,max_steps_reached,D' D' D' D' D' D' D' D' D' D' D' D' D' D' D' D...,50,20043,2026-06-25T16:30:19.312062+00:00
2,eval_001-depth2-episode2,depth_1_onehot,2,R L,BYGBYGBYGOOOOOOOOOYGWYGWYGWGWBGWBGWBRRRRRRRRRY...,False,50,-60.0,True,max_steps_reached,D' D' D' D' D' D' D' D' D' D' D' D' D' D' D' D...,50,20044,2026-06-25T16:30:19.343833+00:00
3,eval_001-depth2-episode3,depth_1_onehot,2,B' D,RRRYYYYYYOOYOOYGGGGGGGGGWRROWWOWWOWWWRRWRRBBBB...,False,50,-60.0,True,max_steps_reached,D' D' D' D' D' D' D' D' D' D' D' D' D' D' D' D...,50,20045,2026-06-25T16:30:19.374307+00:00
4,eval_001-depth2-episode4,depth_1_onehot,2,D D,YYYYYYYYYOOOOOORRRGGGGGGBBBWWWWWWWWWRRRRRROOOB...,True,2,98.0,False,solved,D' D',2,20046,2026-06-25T16:30:19.407217+00:00

None

In [61]:
episodes = pd.read_parquet("../data/logs/depth_1_onehot/eval_001/depth_2/episodes.parquet")
display(episodes.head())

,episode_id,model_version,scramble_depth,scramble_sequence,start_state,solved,total_steps,total_reward,timeout,termination_reason,moves_taken,moves_taken_count,seed,timestamp
0,eval_001-depth2-episode0,depth_1_onehot,2,L U',YYYYYYBBBYGGOOOOOORRRYGGYGGGWWGWWGWWBBWRRRRRRO...,False,50,-60.0,True,max_steps_reached,D' D' D' D' D' D' D' D' D' D' D' D' D' D' D' D...,50,20042,2026-06-25T16:30:19.275383+00:00
1,eval_001-depth2-episode1,depth_1_onehot,2,U B',RRGYYYYYYBBYOOYOOYOOOGGGGGGWWWWWWOOBWGGWRRWRRR...,False,50,-60.0,True,max_steps_reached,D' D' D' D' D' D' D' D' D' D' D' D' D' D' D' D...,50,20043,2026-06-25T16:30:19.312062+00:00
2,eval_001-depth2-episode2,depth_1_onehot,2,R L,BYGBYGBYGOOOOOOOOOYGWYGWYGWGWBGWBGWBRRRRRRRRRY...,False,50,-60.0,True,max_steps_reached,D' D' D' D' D' D' D' D' D' D' D' D' D' D' D' D...,50,20044,2026-06-25T16:30:19.343833+00:00
3,eval_001-depth2-episode3,depth_1_onehot,2,B' D,RRRYYYYYYOOYOOYGGGGGGGGGWRROWWOWWOWWWRRWRRBBBB...,False,50,-60.0,True,max_steps_reached,D' D' D' D' D' D' D' D' D' D' D' D' D' D' D' D...,50,20045,2026-06-25T16:30:19.374307+00:00
4,eval_001-depth2-episode4,depth_1_onehot,2,D D,YYYYYYYYYOOOOOORRRGGGGGGBBBWWWWWWWWWRRRRRROOOB...,True,2,98.0,False,solved,D' D',2,20046,2026-06-25T16:30:19.407217+00:00

In [62]:
solved = episodes[episodes['solved'] == True]

display(solved.head())

print(solved['total_steps'].value_counts())

,episode_id,model_version,scramble_depth,scramble_sequence,start_state,solved,total_steps,total_reward,timeout,termination_reason,moves_taken,moves_taken_count,seed,timestamp
4,eval_001-depth2-episode4,depth_1_onehot,2,D D,YYYYYYYYYOOOOOORRRGGGGGGBBBWWWWWWWWWRRRRRROOOB...,True,2,98.0,False,solved,D' D',2,20046,2026-06-25T16:30:19.407217+00:00
6,eval_001-depth2-episode6,depth_1_onehot,2,R D,YYGYYGYYGOOOOOOGGWGGWGGWRRRWWWWWWBBBRRRRRRYBBY...,True,4,96.0,False,solved,D' R R R,4,20048,2026-06-25T16:30:19.444992+00:00
22,eval_001-depth2-episode22,depth_1_onehot,2,D D,YYYYYYYYYOOOOOORRRGGGGGGBBBWWWWWWWWWRRRRRROOOB...,True,2,98.0,False,solved,D' D',2,20064,2026-06-25T16:30:19.988547+00:00
23,eval_001-depth2-episode23,depth_1_onehot,2,R D',YYGYYGYYGOOOOOOYBBGGWGGWOOOBBBWWWWWWRRRRRRGGWY...,True,6,94.0,False,solved,D' D' D' R R R,6,20065,2026-06-25T16:30:19.990637+00:00
62,eval_001-depth2-episode62,depth_1_onehot,2,R R,YYWYYWYYWOOOOOOOOOGGBGGBGGBWWYWWYWWYRRRRRRRRRG...,True,2,98.0,False,solved,R R,2,20104,2026-06-25T16:30:21.386091+00:00

total_steps
2    3
4    2
6    2
Name: count, dtype: int64

In [63]:
episodes = pd.read_parquet("../data/logs/depth_1_onehot/eval_001/depth_1/episodes.parquet")
display(episodes.head())

,episode_id,model_version,scramble_depth,scramble_sequence,start_state,solved,total_steps,total_reward,timeout,termination_reason,moves_taken,moves_taken_count,seed,timestamp
0,eval_001-depth1-episode0,depth_1_onehot,1,R',YYBYYBYYBOOOOOOOOOGGYGGYGGYWWGWWGWWGRRRRRRRRRW...,True,3,97.0,False,solved,R' R' R',3,10042,2026-06-26T11:38:37.055582+00:00
1,eval_001-depth1-episode1,depth_1_onehot,1,F',YYYYYYOOOWOOWOOWOOGGGGGGGGGRRRWWWWWWRRYRRYRRYB...,True,1,99.0,False,solved,F,1,10043,2026-06-26T11:38:37.138089+00:00
2,eval_001-depth1-episode2,depth_1_onehot,1,U,YYYYYYYYYBBBOOOOOOOOOGGGGGGWWWWWWWWWGGGRRRRRRR...,True,3,97.0,False,solved,U U U,3,10044,2026-06-26T11:38:37.139998+00:00
3,eval_001-depth1-episode3,depth_1_onehot,1,L,BYYBYYBYYOOOOOOOOOYGGYGGYGGGWWGWWGWWRRRRRRRRRB...,False,50,-60.0,True,max_steps_reached,D' D' D' D' D' D' D' D' D' D' D' D' D' D' D' D...,50,10045,2026-06-26T11:38:37.143846+00:00
4,eval_001-depth1-episode4,depth_1_onehot,1,L',GYYGYYGYYOOOOOOOOOWGGWGGWGGBWWBWWBWWRRRRRRRRRB...,False,50,-60.0,True,max_steps_reached,D' D' D' D' D' D' D' D' D' D' D' D' D' D' D' D...,50,10046,2026-06-26T11:38:37.205747+00:00

In [64]:
solved = episodes[episodes['solved'] == True]

display(solved.head())

print(solved['start_state'].value_counts())

,episode_id,model_version,scramble_depth,scramble_sequence,start_state,solved,total_steps,total_reward,timeout,termination_reason,moves_taken,moves_taken_count,seed,timestamp
0,eval_001-depth1-episode0,depth_1_onehot,1,R',YYBYYBYYBOOOOOOOOOGGYGGYGGYWWGWWGWWGRRRRRRRRRW...,True,3,97.0,False,solved,R' R' R',3,10042,2026-06-26T11:38:37.055582+00:00
1,eval_001-depth1-episode1,depth_1_onehot,1,F',YYYYYYOOOWOOWOOWOOGGGGGGGGGRRRWWWWWWRRYRRYRRYB...,True,1,99.0,False,solved,F,1,10043,2026-06-26T11:38:37.138089+00:00
2,eval_001-depth1-episode2,depth_1_onehot,1,U,YYYYYYYYYBBBOOOOOOOOOGGGGGGWWWWWWWWWGGGRRRRRRR...,True,3,97.0,False,solved,U U U,3,10044,2026-06-26T11:38:37.139998+00:00
5,eval_001-depth1-episode5,depth_1_onehot,1,D,YYYYYYYYYOOOOOOGGGGGGGGGRRRWWWWWWWWWRRRRRRBBBB...,True,1,99.0,False,solved,D',1,10047,2026-06-26T11:38:37.268556+00:00
6,eval_001-depth1-episode6,depth_1_onehot,1,B,OOOYYYYYYOOWOOWOOWGGGGGGGGGWWWWWWRRRYRRYRRYRRB...,True,3,97.0,False,solved,B B B,3,10048,2026-06-26T11:38:37.270212+00:00

start_state
YYYYYYYYYBBBOOOOOOOOOGGGGGGWWWWWWWWWGGGRRRRRRRRRBBBBBB    11
YYYYYYYYYGGGOOOOOORRRGGGGGGWWWWWWWWWBBBRRRRRROOOBBBBBB    10
OOOYYYYYYOOWOOWOOWGGGGGGGGGWWWWWWRRRYRRYRRYRRBBBBBBBBB     9
YYYYYYYYYOOOOOOGGGGGGGGGRRRWWWWWWWWWRRRRRRBBBBBBBBBOOO     8
RRRYYYYYYOOYOOYOOYGGGGGGGGGWWWWWWOOOWRRWRRWRRBBBBBBBBB     8
YYGYYGYYGOOOOOOOOOGGWGGWGGWWWBWWBWWBRRRRRRRRRYBBYBBYBB     8
YYYYYYOOOWOOWOOWOOGGGGGGGGGRRRWWWWWWRRYRRYRRYBBBBBBBBB     7
YYYYYYYYYOOOOOOBBBGGGGGGOOOWWWWWWWWWRRRRRRGGGBBBBBBRRR     7
YYBYYBYYBOOOOOOOOOGGYGGYGGYWWGWWGWWGRRRRRRRRRWBBWBBWBB     5
YYYYYYRRRYOOYOOYOOGGGGGGGGGOOOWWWWWWRRWRRWRRWBBBBBBBBB     4
Name: count, dtype: int64

In [65]:
df = pd.read_parquet("../data/processed/training/parquet/depth_1.parquet")
print(df["scramble_moves"].value_counts())

scramble_moves
D     1
U     1
F     1
L     1
D'    1
F'    1
L'    1
R'    1
R     1
U'    1
B'    1
B     1
Name: count, dtype: int64

In [66]:
episodes = pd.read_parquet("../data/logs/depth_1_onehot_2000/eval_001/depth_1/episodes.parquet")
display(episodes.head())

,episode_id,model_version,scramble_depth,scramble_sequence,start_state,solved,total_steps,total_reward,timeout,termination_reason,moves_taken,moves_taken_count,seed,timestamp
0,eval_001-depth1-episode0,depth_1_onehot_2000,1,D,YYYYYYYYYOOOOOOGGGGGGGGGRRRWWWWWWWWWRRRRRRBBBB...,True,1,99.0,False,solved,D',1,None,2026-06-29T13:41:59.352069+00:00
1,eval_001-depth1-episode1,depth_1_onehot_2000,1,U,YYYYYYYYYBBBOOOOOOOOOGGGGGGWWWWWWWWWGGGRRRRRRR...,True,3,97.0,False,solved,U U U,3,None,2026-06-29T13:41:59.408367+00:00
2,eval_001-depth1-episode2,depth_1_onehot_2000,1,F,YYYYYYRRRYOOYOOYOOGGGGGGGGGOOOWWWWWWRRWRRWRRWB...,True,3,97.0,False,solved,F F F,3,None,2026-06-29T13:41:59.411201+00:00
3,eval_001-depth1-episode3,depth_1_onehot_2000,1,L,BYYBYYBYYOOOOOOOOOYGGYGGYGGGWWGWWGWWRRRRRRRRRB...,False,50,-60.0,True,max_steps_reached,B F F F F F F F F F F F F F F F F F F F F F F ...,50,None,2026-06-29T13:41:59.413552+00:00
4,eval_001-depth1-episode4,depth_1_onehot_2000,1,D',YYYYYYYYYOOOOOOBBBGGGGGGOOOWWWWWWWWWRRRRRRGGGB...,True,3,97.0,False,solved,D' D' D',3,None,2026-06-29T13:41:59.453776+00:00

In [67]:
solved = episodes[episodes['solved'] == True]

display(solved.head())

print(solved['start_state'].value_counts())

,episode_id,model_version,scramble_depth,scramble_sequence,start_state,solved,total_steps,total_reward,timeout,termination_reason,moves_taken,moves_taken_count,seed,timestamp
0,eval_001-depth1-episode0,depth_1_onehot_2000,1,D,YYYYYYYYYOOOOOOGGGGGGGGGRRRWWWWWWWWWRRRRRRBBBB...,True,1,99.0,False,solved,D',1,None,2026-06-29T13:41:59.352069+00:00
1,eval_001-depth1-episode1,depth_1_onehot_2000,1,U,YYYYYYYYYBBBOOOOOOOOOGGGGGGWWWWWWWWWGGGRRRRRRR...,True,3,97.0,False,solved,U U U,3,None,2026-06-29T13:41:59.408367+00:00
2,eval_001-depth1-episode2,depth_1_onehot_2000,1,F,YYYYYYRRRYOOYOOYOOGGGGGGGGGOOOWWWWWWRRWRRWRRWB...,True,3,97.0,False,solved,F F F,3,None,2026-06-29T13:41:59.411201+00:00
4,eval_001-depth1-episode4,depth_1_onehot_2000,1,D',YYYYYYYYYOOOOOOBBBGGGGGGOOOWWWWWWWWWRRRRRRGGGB...,True,3,97.0,False,solved,D' D' D',3,None,2026-06-29T13:41:59.453776+00:00
5,eval_001-depth1-episode5,depth_1_onehot_2000,1,F',YYYYYYOOOWOOWOOWOOGGGGGGGGGRRRWWWWWWRRYRRYRRYB...,True,1,99.0,False,solved,F,1,None,2026-06-29T13:41:59.456860+00:00

start_state
YYYYYYYYYOOOOOOGGGGGGGGGRRRWWWWWWWWWRRRRRRBBBBBBBBBOOO    9
YYYYYYYYYBBBOOOOOOOOOGGGGGGWWWWWWWWWGGGRRRRRRRRRBBBBBB    9
YYYYYYRRRYOOYOOYOOGGGGGGGGGOOOWWWWWWRRWRRWRRWBBBBBBBBB    9
YYYYYYYYYOOOOOOBBBGGGGGGOOOWWWWWWWWWRRRRRRGGGBBBBBBRRR    8
YYYYYYOOOWOOWOOWOOGGGGGGGGGRRRWWWWWWRRYRRYRRYBBBBBBBBB    8
YYBYYBYYBOOOOOOOOOGGYGGYGGYWWGWWGWWGRRRRRRRRRWBBWBBWBB    8
YYGYYGYYGOOOOOOOOOGGWGGWGGWWWBWWBWWBRRRRRRRRRYBBYBBYBB    8
YYYYYYYYYGGGOOOOOORRRGGGGGGWWWWWWWWWBBBRRRRRROOOBBBBBB    8
RRRYYYYYYOOYOOYOOYGGGGGGGGGWWWWWWOOOWRRWRRWRRBBBBBBBBB    8
OOOYYYYYYOOWOOWOOWGGGGGGGGGWWWWWWRRRYRRYRRYRRBBBBBBBBB    8
Name: count, dtype: int64

In [68]:
history = pd.read_csv("../models/artifacts/ppo/depth_1_2_onehot/v001/history.csv")

display(history.head())
print(history.shape)

,approx_kl,clip_fraction,entropy,explained_variance,loss,mean_episode_length,mean_episode_reward,policy_loss,timesteps,train_solve_rate,value_loss,evaluation
0,0.004274,0.025586,2.481479,-0.057582,-0.040789,9.57,-0.1772,-0.021377,2048,0.05,0.010806,NaN
1,0.005242,0.056885,2.475433,0.020987,-0.048012,9.06,-0.1086,-0.030735,4096,0.11,0.014955,NaN
2,0.007213,0.081982,2.462716,0.062328,-0.051469,9.16,-0.1161,-0.035497,6144,0.10,0.017311,NaN
3,0.009122,0.137402,2.444471,-0.022117,-0.057795,9.39,-0.1524,-0.042527,8192,0.07,0.018354,NaN
4,0.011967,0.192188,2.412887,0.132290,-0.059176,9.29,-0.1319,-0.047032,10240,0.09,0.023969,"{""by_depth"":{""1"":{""action_counts"":{""B"":1,""B'"":..."

(489, 12)

In [69]:
fig1 = px.bar(history, x='timesteps', y='mean_episode_reward')
fig1.show()

In [70]:
history = pd.read_csv("../models/artifacts/ppo/depth_1_onehot/v009/history.csv")

display(history.head())
print(history.shape)

fig1 = px.bar(history, x='timesteps', y='train_solve_rate')
fig1.show()

,approx_kl,clip_fraction,entropy,explained_variance,loss,mean_episode_length,mean_episode_reward,policy_loss,timesteps,train_solve_rate,value_loss,evaluation
0,0.002966,0.021094,2.480210,-0.025382,-0.037252,4.80,-0.1060,-0.026141,2048,0.05,0.027382,NaN
1,0.008856,0.118555,2.464976,0.019126,-0.047871,4.42,0.0208,-0.040258,4096,0.16,0.034075,NaN
2,0.018618,0.251221,2.400262,0.043592,-0.054333,4.30,0.0655,-0.056089,6144,0.20,0.051517,NaN
3,0.023883,0.371143,2.273853,0.128468,-0.053463,3.78,0.2192,-0.084891,8192,0.34,0.108332,NaN
4,0.025069,0.460791,2.098712,0.232203,-0.056918,3.16,0.4034,-0.106189,10240,0.50,0.140518,"{""by_depth"":{""1"":{""action_counts"":{""B"":1,""B'"":..."

(489, 12)

In [71]:
history = pd.read_csv("../models/artifacts/ppo/depth_1_5_onehot/v001/history.csv")

history_5 = history[history['curriculum_depth'] == 1]

print(history_5.shape)
solve_rate = history.copy()

solve_rate['avg_solve'] = solve_rate.groupby('curriculum_depth')['train_solve_rate'].transform('mean')

display(solve_rate[['curriculum_depth', 'avg_solve']])

depth_stats = solve_rate.groupby('curriculum_depth').agg(
    depth_count=('curriculum_depth', 'count'),
    avg_solve=('train_solve_rate', 'mean')
)

display(depth_stats)

display(history_5.head())
print(history.shape)
print(history['curriculum_depth'].value_counts())

fig1 = px.line(history_5, x='timesteps', y='train_solve_rate')
fig1.show()

(5, 17)

     curriculum_depth  avg_solve
0                   1   0.248000
1                   1   0.248000
2                   1   0.248000
3                   1   0.248000
4                   1   0.248000
..                ...        ...
484                 5   0.864352
485                 5   0.864352
486                 5   0.864352
487                 5   0.864352
488                 5   0.864352

[489 rows x 2 columns]

                  depth_count  avg_solve
curriculum_depth
1                           5   0.248000
2                           5   0.668000
3                          10   0.838000
4                         122   0.857377
5                         347   0.864352

,timesteps,policy_loss,value_loss,entropy,approx_kl,clip_fraction,loss,explained_variance,mean_episode_reward,mean_episode_length,train_solve_rate,timeout_rate,inverse_move_rate,curriculum_depth,curriculum_sampling_weights,evaluation,curriculum_evaluation
0,2048,-0.034626,0.040052,2.478456,0.004873,0.060498,-0.039385,-0.018794,-0.0342,2.82,0.09,0.91,0.035461,1,"{""1"":1.0}",NaN,NaN
1,4096,-0.052345,0.048615,2.438512,0.015399,0.203027,-0.052423,0.009953,-0.0474,2.84,0.08,0.92,0.049296,1,"{""1"":1.0}",NaN,NaN
2,6144,-0.082350,0.099016,2.311139,0.030721,0.412158,-0.055954,0.052768,0.0530,2.70,0.17,0.83,0.051852,1,"{""1"":1.0}",NaN,NaN
3,8192,-0.095648,0.176465,2.102715,0.028169,0.433105,-0.028443,0.148479,0.2839,2.36,0.38,0.62,0.088983,1,"{""1"":1.0}",NaN,NaN
4,10240,-0.084767,0.225571,1.843426,0.017972,0.335449,0.009585,0.203968,0.4382,2.18,0.52,0.48,0.110092,1,"{""1"":1.0}","{""by_depth"":{""1"":{""action_counts"":{""B"":1,""B'"":...","{""advanced_curriculum"":true,""curriculum_depth""..."

(489, 17)
curriculum_depth
5    347
4    122
3     10
1      5
2      5
Name: count, dtype: int64

In [72]:
history = pd.read_csv("../models/artifacts/ppo/depth_1_3_onehot/v001/history.csv")

display(history.head())
print(history.shape)

fig1 = px.bar(history, x='timesteps', y='mean_episode_reward')
fig1.show()

,timesteps,policy_loss,value_loss,entropy,approx_kl,clip_fraction,loss,explained_variance,mean_episode_reward,mean_episode_length,train_solve_rate,timeout_rate,inverse_move_rate,evaluation
0,2048,-0.027216,0.003837,2.481435,0.003694,0.025146,-0.050111,-0.187237,-0.3589,19.64,0.02,0.98,0.086049,NaN
1,4096,-0.060968,0.001468,2.471692,0.008021,0.118506,-0.084951,0.040781,-0.3765,20.00,0.00,1.00,0.076500,NaN
2,6144,-0.046633,0.004367,2.460479,0.007292,0.100293,-0.069055,0.179114,-0.3348,19.43,0.03,0.97,0.075656,NaN
3,8192,-0.048295,0.005037,2.445252,0.008451,0.119873,-0.070229,0.079202,-0.3437,19.47,0.03,0.97,0.084232,NaN
4,10240,-0.055671,0.004503,2.431901,0.009390,0.152148,-0.077738,0.070343,-0.3156,19.06,0.05,0.95,0.083945,"{""by_depth"":{""1"":{""action_counts"":{""B"":0,""B'"":..."

(245, 14)

In [73]:
history = pd.read_csv("../models/artifacts/ppo/depth_1_10_onehot/v004/history.csv")

display(history.head())
print(history.shape)

fig1 = px.bar(history, x='timesteps', y='mean_episode_reward')
fig1.show()

,timesteps,policy_loss,value_loss,entropy,approx_kl,clip_fraction,loss,explained_variance,mean_episode_reward,mean_episode_length,train_solve_rate,timeout_rate,inverse_move_rate,curriculum_depth,curriculum_sampling_weights,evaluation,curriculum_evaluation
0,2048,-0.034626,0.040052,2.478456,0.004873,0.060498,-0.039385,-0.018794,-0.0342,2.82,0.09,0.91,0.035461,1,"{""1"":1.0}",NaN,NaN
1,4096,-0.052345,0.048615,2.438512,0.015399,0.203027,-0.052423,0.009953,-0.0474,2.84,0.08,0.92,0.049296,1,"{""1"":1.0}",NaN,NaN
2,6144,-0.082350,0.099016,2.311139,0.030721,0.412158,-0.055954,0.052768,0.0530,2.70,0.17,0.83,0.051852,1,"{""1"":1.0}",NaN,NaN
3,8192,-0.095648,0.176465,2.102715,0.028169,0.433105,-0.028443,0.148479,0.2839,2.36,0.38,0.62,0.088983,1,"{""1"":1.0}",NaN,NaN
4,10240,-0.084767,0.225571,1.843426,0.017972,0.335449,0.009585,0.203968,0.4382,2.18,0.52,0.48,0.110092,1,"{""1"":1.0}","{""by_depth"":{""1"":{""action_counts"":{""B"":1,""B'"":...","{""advanced_curriculum"":true,""curriculum_depth""..."

(977, 17)

In [74]:
episodes = pd.read_parquet("../data/logs/depth_1_3_v1/eval_001/depth_1/episodes.parquet")
display(episodes.head())


solved = episodes[episodes['solved'] == True]

display(solved.head())

print(solved['start_state'].value_counts())
print(solved['scramble_depth'].value_counts())

,episode_id,model_version,scramble_depth,scramble_sequence,start_state,solved,total_steps,total_reward,timeout,termination_reason,moves_taken,moves_taken_count,seed,timestamp
0,eval_001-depth1-episode0,depth_1_3_v1,1,D,YYYYYYYYYOOOOOOGGGGGGGGGRRRWWWWWWWWWRRRRRRBBBB...,True,1,0.99,False,solved,D',1,None,2026-07-01T11:38:27.477115+00:00
1,eval_001-depth1-episode1,depth_1_3_v1,1,U,YYYYYYYYYBBBOOOOOOOOOGGGGGGWWWWWWWWWGGGRRRRRRR...,True,3,0.97,False,solved,U U U,3,None,2026-07-01T11:38:27.560329+00:00
2,eval_001-depth1-episode2,depth_1_3_v1,1,F,YYYYYYRRRYOOYOOYOOGGGGGGGGGOOOWWWWWWRRWRRWRRWB...,True,1,0.99,False,solved,F',1,None,2026-07-01T11:38:27.564453+00:00
3,eval_001-depth1-episode3,depth_1_3_v1,1,L,BYYBYYBYYOOOOOOOOOYGGYGGYGGGWWGWWGWWRRRRRRRRRB...,True,1,0.99,False,solved,L',1,None,2026-07-01T11:38:27.566193+00:00
4,eval_001-depth1-episode4,depth_1_3_v1,1,D',YYYYYYYYYOOOOOOBBBGGGGGGOOOWWWWWWWWWRRRRRRGGGB...,True,1,0.99,False,solved,D,1,None,2026-07-01T11:38:27.567712+00:00

,episode_id,model_version,scramble_depth,scramble_sequence,start_state,solved,total_steps,total_reward,timeout,termination_reason,moves_taken,moves_taken_count,seed,timestamp
0,eval_001-depth1-episode0,depth_1_3_v1,1,D,YYYYYYYYYOOOOOOGGGGGGGGGRRRWWWWWWWWWRRRRRRBBBB...,True,1,0.99,False,solved,D',1,None,2026-07-01T11:38:27.477115+00:00
1,eval_001-depth1-episode1,depth_1_3_v1,1,U,YYYYYYYYYBBBOOOOOOOOOGGGGGGWWWWWWWWWGGGRRRRRRR...,True,3,0.97,False,solved,U U U,3,None,2026-07-01T11:38:27.560329+00:00
2,eval_001-depth1-episode2,depth_1_3_v1,1,F,YYYYYYRRRYOOYOOYOOGGGGGGGGGOOOWWWWWWRRWRRWRRWB...,True,1,0.99,False,solved,F',1,None,2026-07-01T11:38:27.564453+00:00
3,eval_001-depth1-episode3,depth_1_3_v1,1,L,BYYBYYBYYOOOOOOOOOYGGYGGYGGGWWGWWGWWRRRRRRRRRB...,True,1,0.99,False,solved,L',1,None,2026-07-01T11:38:27.566193+00:00
4,eval_001-depth1-episode4,depth_1_3_v1,1,D',YYYYYYYYYOOOOOOBBBGGGGGGOOOWWWWWWWWWRRRRRRGGGB...,True,1,0.99,False,solved,D,1,None,2026-07-01T11:38:27.567712+00:00

start_state
YYYYYYYYYOOOOOOGGGGGGGGGRRRWWWWWWWWWRRRRRRBBBBBBBBBOOO    1
YYYYYYYYYBBBOOOOOOOOOGGGGGGWWWWWWWWWGGGRRRRRRRRRBBBBBB    1
YYYYYYRRRYOOYOOYOOGGGGGGGGGOOOWWWWWWRRWRRWRRWBBBBBBBBB    1
BYYBYYBYYOOOOOOOOOYGGYGGYGGGWWGWWGWWRRRRRRRRRBBWBBWBBW    1
YYYYYYYYYOOOOOOBBBGGGGGGOOOWWWWWWWWWRRRRRRGGGBBBBBBRRR    1
YYYYYYOOOWOOWOOWOOGGGGGGGGGRRRWWWWWWRRYRRYRRYBBBBBBBBB    1
GYYGYYGYYOOOOOOOOOWGGWGGWGGBWWBWWBWWRRRRRRRRRBBYBBYBBY    1
YYBYYBYYBOOOOOOOOOGGYGGYGGYWWGWWGWWGRRRRRRRRRWBBWBBWBB    1
YYGYYGYYGOOOOOOOOOGGWGGWGGWWWBWWBWWBRRRRRRRRRYBBYBBYBB    1
YYYYYYYYYGGGOOOOOORRRGGGGGGWWWWWWWWWBBBRRRRRROOOBBBBBB    1
RRRYYYYYYOOYOOYOOYGGGGGGGGGWWWWWWOOOWRRWRRWRRBBBBBBBBB    1
OOOYYYYYYOOWOOWOOWGGGGGGGGGWWWWWWRRRYRRYRRYRRBBBBBBBBB    1
Name: count, dtype: int64
scramble_depth
1    12
Name: count, dtype: int64

In [80]:
episodes = pd.read_parquet("../data/logs/depth_1_10_v7/eval_001/depth_5/episodes.parquet")
display(episodes.head())

print(episodes['start_state'].value_counts())
print(episodes['scramble_depth'].value_counts())


solved = episodes[episodes['solved'] == True]

display(solved.head())

print(solved['start_state'].value_counts())
print(solved['scramble_depth'].value_counts())

,episode_id,model_version,scramble_depth,scramble_sequence,start_state,solved,total_steps,total_reward,timeout,termination_reason,moves_taken,moves_taken_count,seed,timestamp
0,eval_001-depth5-episode0,depth_1_10_v7,5,B L B D L',OWWYYYBYYOOROORYGGYGGRGGRRRGGGBWWBWWYRRYRWOOWB...,False,50,-3.0,True,max_steps_reached,B' B' B B' B B' B B' B B' B B' B B' B B' B B' ...,50,None,2026-07-11T18:25:16.041748+00:00
1,eval_001-depth5-episode1,depth_1_10_v7,5,F' D' F' B R',OOYYYRWWRWWROOBWWRGGBGGYGGBYYORWORRWYROYROYGOG...,False,50,-2.8,True,max_steps_reached,B' F F D D F F' F F' F F' F F' F F' F F' F F' ...,50,None,2026-07-11T18:25:16.096356+00:00
2,eval_001-depth5-episode2,depth_1_10_v7,5,L B' D' F L',ORROYYYRRBOBYOYYBBBYYWGGGGGROOBWOWGOWWORRGGWYW...,False,50,-0.6,True,max_steps_reached,F F F B L' F F F F F F F F F F F F F F F F F F...,50,None,2026-07-11T18:25:16.151012+00:00
3,eval_001-depth5-episode3,depth_1_10_v7,5,L' F' L U L',WYYGYYOYYBBBWOOBOOGOOGGGWWWRRRBWWRWWGRYGRYGRGR...,False,50,-2.9,True,max_steps_reached,U' F L F F' F F' F F' F F' F F' F F' F F' F F'...,50,None,2026-07-11T18:25:16.204253+00:00
4,eval_001-depth5-episode4,depth_1_10_v7,5,D L L B B,WWYWYYWYYOOROORGGBOGGBGGBRRYWWYWWYYWGBBORRORRG...,False,50,-2.9,True,max_steps_reached,B B D' B B' B B' B B' B B' B B' B B' B B' B B'...,50,None,2026-07-11T18:25:16.259540+00:00

start_state
OWWYYYBYYOOROORYGGYGGRGGRRRGGGBWWBWWYRRYRWOOWBBBBBBOOW    1
OOYYYRWWRWWROOBWWRGGBGGYGGBYYORWORRWYROYROYGOGBBWBBGBB    1
ORROYYYRRBOBYOYYBBBYYWGGGGGROOBWOWGOWWORRGGWYWWGBBBWRR    1
WYYGYYOYYBBBWOOBOOGOOGGGWWWRRRBWWRWWGRYGRYGRGRROBBOBBY    1
WWYWYYWYYOOROORGGBOGGBGGBRRYWWYWWYYWGBBORRORRGOOGBBRBB    1
                                                         ..
WOGWYGOOBYOOWOOYWWWWRGGGBBRRRGBWBBRBRRGRRYYYWYBGYBGOYO    1
YYWBYYBYYOOGOOOOOORGGYGGYGGGWWGWWBRWRWWRRRYRRRBBBBBBWO    1
RRWGYGGRGYYGOOOYYWOWOBGWBGOYOBYWBOORYWWWRRWRRRGGYBBBBB    1
GOOYYYBOOWGWWOWYOYRGGRGGRBBGRRYWWBRRYBWYRWYRWBBOBBOGGO    1
GGRYYRRRBOBYYOYYORGGYWGGOGGBOOBWWBOGORWBRRWWWBWWOBYYBR    1
Name: count, Length: 100, dtype: int64
scramble_depth
5    100
Name: count, dtype: int64

,episode_id,model_version,scramble_depth,scramble_sequence,start_state,solved,total_steps,total_reward,timeout,termination_reason,moves_taken,moves_taken_count,seed,timestamp
25,eval_001-depth5-episode25,depth_1_10_v7,5,D D B' L' U,BGGYYRYYRBBYOOYRRYOOYWGGRBBGWWGWWGOOWGGRROWWWR...,True,5,0.95,False,solved,U' L B D' D',5,None,2026-07-11T18:25:17.362942+00:00
63,eval_001-depth5-episode63,depth_1_10_v7,5,R' R' B' L' F,GRRGYWYRRGOYYOYWOWOWWGGGBBBOOOBWYBOORRGRRWWWYB...,True,5,0.95,False,solved,F' L B R' R',5,None,2026-07-11T18:25:19.297448+00:00

start_state
BGGYYRYYRBBYOOYRRYOOYWGGRBBGWWGWWGOOWGGRROWWWRROBBYBBO    1
GRRGYWYRRGOYYOYWOWOWWGGGBBBOOOBWYBOORRGRRWWWYBBYBBYGGR    1
Name: count, dtype: int64
scramble_depth
5    2
Name: count, dtype: int64

In [76]:
episodes = pd.read_parquet("../data/logs/depth_1_2_v1/eval_001/depth_2/episodes.parquet")
display(episodes.head())

print(episodes['start_state'].value_counts())
print(episodes['scramble_depth'].value_counts())


solved = episodes[episodes['solved'] == True]

display(solved.head())

print(solved['start_state'].value_counts())
print(solved['scramble_depth'].value_counts())

,episode_id,model_version,scramble_depth,scramble_sequence,start_state,solved,total_steps,total_reward,timeout,termination_reason,moves_taken,moves_taken_count,seed,timestamp
0,eval_001-depth2-episode0,depth_1_2_v1,2,F' L,BYYBYYBOOWOOWOOWOOYGGYGGOGGGRRGWWGWWRRRRRRYYYB...,True,2,0.98,False,solved,L' F,2,None,2026-07-01T12:17:00.745145+00:00
1,eval_001-depth2-episode1,depth_1_2_v1,2,L U',YYYYYYBBBYGGOOOOOORRRYGGYGGGWWGWWGWWBBWRRRRRRO...,True,2,0.98,False,solved,U L',2,None,2026-07-01T12:17:00.749505+00:00
2,eval_001-depth2-episode2,depth_1_2_v1,2,F' D',YYYYYYOOOWOOWOOBBBGGGGGGWOORWWRWWRWWRRYRRYGGGB...,True,2,0.98,False,solved,D F,2,None,2026-07-01T12:17:00.753814+00:00
3,eval_001-depth2-episode3,depth_1_2_v1,2,F' B,OOOYYYOOOWOWWOWWOWGGGGGGGGGRRRWWWRRRYRYYRYYRYB...,True,2,0.98,False,solved,F B',2,None,2026-07-01T12:17:00.757370+00:00
4,eval_001-depth2-episode4,depth_1_2_v1,2,B R',OOBYYBYYBWWWOOOOOOGGOGGYGGYWWGWWGRRGYRRYRRYRRR...,True,2,0.98,False,solved,R B',2,None,2026-07-01T12:17:00.761025+00:00

start_state
BYYBYYBOOWOOWOOWOOYGGYGGOGGGRRGWWGWWRRRRRRYYYBBWBBWBBR    1
YYYYYYBBBYGGOOOOOORRRYGGYGGGWWGWWGWWBBWRRRRRROOOBBWBBW    1
YYYYYYOOOWOOWOOBBBGGGGGGWOORWWRWWRWWRRYRRYGGGBBBBBBRRY    1
OOOYYYOOOWOWWOWWOWGGGGGGGGGRRRWWWRRRYRYYRYYRYBBBBBBBBB    1
OOBYYBYYBWWWOOOOOOGGOGGYGGYWWGWWGRRGYRRYRRYRRRBBWBBWBB    1
                                                         ..
RYYBYYBYYOOOOOOBBBYGGYGGYOOGWWGWWOWWGRRGRRGRRBBWBBWRRW    1
YYYYYYYYYBBBOOOGGGOOOGGGRRRWWWWWWWWWGGGRRRBBBRRRBBBOOO    1
YYWYYWYYWOOOOOOOOOGGBGGBGGBWWYWWYWWYRRRRRRRRRGBBGBBGBB    1
YYYYYYBRRYOOYOOYGGRGGRGGRGGGOOWWWWWWRRWRRWBBWBBBBBBOOO    1
GYYGYYGOOWOOWOOWOORGGWGGWGGBRRBWWBWWYYYRRRRRRBBOBBYBBY    1
Name: count, Length: 100, dtype: int64
scramble_depth
2    100
Name: count, dtype: int64

,episode_id,model_version,scramble_depth,scramble_sequence,start_state,solved,total_steps,total_reward,timeout,termination_reason,moves_taken,moves_taken_count,seed,timestamp
0,eval_001-depth2-episode0,depth_1_2_v1,2,F' L,BYYBYYBOOWOOWOOWOOYGGYGGOGGGRRGWWGWWRRRRRRYYYB...,True,2,0.98,False,solved,L' F,2,None,2026-07-01T12:17:00.745145+00:00
1,eval_001-depth2-episode1,depth_1_2_v1,2,L U',YYYYYYBBBYGGOOOOOORRRYGGYGGGWWGWWGWWBBWRRRRRRO...,True,2,0.98,False,solved,U L',2,None,2026-07-01T12:17:00.749505+00:00
2,eval_001-depth2-episode2,depth_1_2_v1,2,F' D',YYYYYYOOOWOOWOOBBBGGGGGGWOORWWRWWRWWRRYRRYGGGB...,True,2,0.98,False,solved,D F,2,None,2026-07-01T12:17:00.753814+00:00
3,eval_001-depth2-episode3,depth_1_2_v1,2,F' B,OOOYYYOOOWOWWOWWOWGGGGGGGGGRRRWWWRRRYRYYRYYRYB...,True,2,0.98,False,solved,F B',2,None,2026-07-01T12:17:00.757370+00:00
4,eval_001-depth2-episode4,depth_1_2_v1,2,B R',OOBYYBYYBWWWOOOOOOGGOGGYGGYWWGWWGRRGYRRYRRYRRR...,True,2,0.98,False,solved,R B',2,None,2026-07-01T12:17:00.761025+00:00

start_state
BYYBYYBOOWOOWOOWOOYGGYGGOGGGRRGWWGWWRRRRRRYYYBBWBBWBBR    1
YYYYYYBBBYGGOOOOOORRRYGGYGGGWWGWWGWWBBWRRRRRROOOBBWBBW    1
YYYYYYOOOWOOWOOBBBGGGGGGWOORWWRWWRWWRRYRRYGGGBBBBBBRRY    1
OOOYYYOOOWOWWOWWOWGGGGGGGGGRRRWWWRRRYRYYRYYRYBBBBBBBBB    1
OOBYYBYYBWWWOOOOOOGGOGGYGGYWWGWWGRRGYRRYRRYRRRBBWBBWBB    1
                                                         ..
RYYBYYBYYOOOOOOBBBYGGYGGYOOGWWGWWOWWGRRGRRGRRBBWBBWRRW    1
YYYYYYYYYBBBOOOGGGOOOGGGRRRWWWWWWWWWGGGRRRBBBRRRBBBOOO    1
YYWYYWYYWOOOOOOOOOGGBGGBGGBWWYWWYWWYRRRRRRRRRGBBGBBGBB    1
YYYYYYBRRYOOYOOYGGRGGRGGRGGGOOWWWWWWRRWRRWBBWBBBBBBOOO    1
GYYGYYGOOWOOWOOWOORGGWGGWGGBRRBWWBWWYYYRRRRRRBBOBBYBBY    1
Name: count, Length: 100, dtype: int64
scramble_depth
2    100
Name: count, dtype: int64

In [77]:
history = pd.read_csv("../models/artifacts/ppo/depth_1_10_onehot/v004/history.csv")

history_5 = history[history['curriculum_depth'] == 6]

print(history_5.shape)
solve_rate = history.copy()

solve_rate['avg_solve'] = solve_rate.groupby('curriculum_depth')['train_solve_rate'].transform('mean')

display(solve_rate[['curriculum_depth', 'avg_solve']])

depth_stats = solve_rate.groupby('curriculum_depth').agg(
    depth_count=('curriculum_depth', 'count'),
    avg_solve=('train_solve_rate', 'mean'),
    avg_timeout=('timeout_rate', 'mean'),
    min_timeout=('timeout_rate', 'min'),
    max_timeout=('timeout_rate', 'max'),
    ep_length=('mean_episode_length', 'mean'),
    
)

display(depth_stats)

display(history_5.head())
print(history.shape)
print(history['curriculum_depth'].value_counts())

fig1 = px.line(history_5, x='timesteps', y='entropy')
fig1.show()

(522, 17)

     curriculum_depth  avg_solve
0                   1   0.248000
1                   1   0.248000
2                   1   0.248000
3                   1   0.248000
4                   1   0.248000
..                ...        ...
972                 6   0.741322
973                 6   0.741322
974                 6   0.741322
975                 6   0.741322
976                 6   0.741322

[977 rows x 2 columns]

,depth_count,avg_solve,avg_timeout,min_timeout,max_timeout,ep_length
curriculum_depth,,,,,,
1,5,0.248000,0.752000,0.48,0.92,2.580000
2,5,0.668000,0.332000,0.16,0.59,2.840000
3,5,0.804000,0.196000,0.15,0.25,3.230000
4,147,0.854218,0.145782,0.03,0.35,3.889116
5,293,0.856553,0.143447,0.04,0.31,4.590341
6,522,0.741322,0.258678,0.12,0.43,6.661264

,timesteps,policy_loss,value_loss,entropy,approx_kl,clip_fraction,loss,explained_variance,mean_episode_reward,mean_episode_length,train_solve_rate,timeout_rate,inverse_move_rate,curriculum_depth,curriculum_sampling_weights,evaluation,curriculum_evaluation
455,933888,-0.055533,0.034910,0.567076,0.034449,0.244446,-0.043749,0.591404,0.5093,7.12,0.66,0.34,0.127809,6,"{""1"":0.05,""2"":0.1,""3"":0.1,""4"":0.15,""5"":0.2,""6""...",NaN,NaN
456,935936,-0.033071,0.053248,0.543462,0.022366,0.158325,-0.011881,0.671155,0.5551,7.24,0.70,0.30,0.117403,6,"{""1"":0.05,""2"":0.1,""3"":0.1,""4"":0.15,""5"":0.2,""6""...",NaN,NaN
457,937984,-0.033503,0.051170,0.491767,0.023452,0.170898,-0.012835,0.636614,0.5415,7.30,0.68,0.32,0.091781,6,"{""1"":0.05,""2"":0.1,""3"":0.1,""4"":0.15,""5"":0.2,""6""...",NaN,NaN
458,940032,-0.037619,0.043133,0.504302,0.025071,0.176172,-0.021096,0.674672,0.5847,6.98,0.72,0.28,0.107450,6,"{""1"":0.05,""2"":0.1,""3"":0.1,""4"":0.15,""5"":0.2,""6""...","{""by_depth"":{""6"":{""action_counts"":{""B"":972,""B'...","{""advanced_curriculum"":false,""curriculum_depth..."
459,942080,-0.033139,0.045177,0.487913,0.021685,0.159766,-0.015429,0.704788,0.5375,7.05,0.68,0.32,0.113475,6,"{""1"":0.05,""2"":0.1,""3"":0.1,""4"":0.15,""5"":0.2,""6""...",NaN,NaN

(977, 17)
curriculum_depth
6    522
5    293
4    147
1      5
2      5
3      5
Name: count, dtype: int64

In [78]:
history = pd.read_csv("../models/artifacts/ppo/depth_1_10_onehot/v005/history.csv")

history_5 = history[history['curriculum_depth'] == 6]

print(history_5.shape)
solve_rate = history.copy()

depth_stats = solve_rate.groupby('curriculum_depth').agg(
    depth_count=('curriculum_depth', 'count'),
    avg_solve=('train_solve_rate', 'mean'),
    max_solve=('train_solve_rate', 'max'),
    avg_timeout=('timeout_rate', 'mean'),
    min_timeout=('timeout_rate', 'min'),
    max_timeout=('timeout_rate', 'max'),
    ep_length=('mean_episode_length', 'mean'),
    
)

display(depth_stats)

display(history_5.head())
print(history.shape)
print(history['curriculum_depth'].value_counts())

fig1 = px.line(history_5, x='timesteps', y='entropy')
fig1.show()

(1041, 17)

,depth_count,avg_solve,max_solve,avg_timeout,min_timeout,max_timeout,ep_length
curriculum_depth,,,,,,,
1,5,0.248000,0.52,0.752000,0.48,0.92,2.580000
2,5,0.668000,0.84,0.332000,0.16,0.59,2.840000
3,5,0.804000,0.85,0.196000,0.15,0.25,3.230000
4,127,0.843386,0.95,0.156614,0.05,0.35,3.952520
5,317,0.851640,0.96,0.148360,0.04,0.33,4.617066
6,1041,0.680961,0.85,0.319039,0.15,0.55,7.799760
7,942,0.517452,0.67,0.482548,0.33,0.64,10.309013

,timesteps,policy_loss,value_loss,entropy,approx_kl,clip_fraction,loss,explained_variance,mean_episode_reward,mean_episode_length,train_solve_rate,timeout_rate,inverse_move_rate,curriculum_depth,curriculum_sampling_weights,evaluation,curriculum_evaluation
459,942080,-0.028952,0.070849,0.606290,0.016999,0.146647,0.000409,0.562395,0.4785,8.20,0.64,0.36,0.106098,6,"{""1"":0.02,""2"":0.03,""3"":0.05,""4"":0.1,""5"":0.2,""6...",NaN,NaN
460,944128,-0.040038,0.053014,0.623171,0.026077,0.211230,-0.019762,0.588815,0.2813,8.87,0.49,0.51,0.155581,6,"{""1"":0.02,""2"":0.03,""3"":0.05,""4"":0.1,""5"":0.2,""6...",NaN,NaN
461,946176,-0.034749,0.046209,0.607741,0.030595,0.208105,-0.017722,0.640104,0.3236,8.84,0.52,0.48,0.135747,6,"{""1"":0.02,""2"":0.03,""3"":0.05,""4"":0.1,""5"":0.2,""6...",NaN,NaN
462,948224,-0.046011,0.043271,0.616176,0.032100,0.236956,-0.030538,0.580515,0.3443,8.82,0.54,0.46,0.139456,6,"{""1"":0.02,""2"":0.03,""3"":0.05,""4"":0.1,""5"":0.2,""6...",NaN,NaN
463,950272,-0.040449,0.046827,0.617784,0.029281,0.227620,-0.023213,0.607633,0.3749,8.86,0.56,0.44,0.118510,6,"{""1"":0.02,""2"":0.03,""3"":0.05,""4"":0.1,""5"":0.2,""6...","{""by_depth"":{""6"":{""action_counts"":{""B"":815,""B'...","{""advanced_curriculum"":false,""curriculum_depth..."

(2442, 17)
curriculum_depth
6    1041
7     942
5     317
4     127
1       5
2       5
3       5
Name: count, dtype: int64

In [79]:
history = pd.read_csv("../models/artifacts/ppo/depth_1_10_onehot/v007/history.csv")

history_5 = history[history['curriculum_depth'] == 6]

print(history_5.shape)
solve_rate = history.copy()

depth_stats = solve_rate.groupby('curriculum_depth').agg(
    depth_count=('curriculum_depth', 'count'),
    avg_solve=('train_solve_rate', 'mean'),
    max_solve=('train_solve_rate', 'max'),
    avg_timeout=('timeout_rate', 'mean'),
    min_timeout=('timeout_rate', 'min'),
    max_timeout=('timeout_rate', 'max'),
    ep_length=('mean_episode_length', 'mean'),
    
)

display(depth_stats)

display(history_5.head())
print(history.shape)
print(history['curriculum_depth'].value_counts())

fig1 = px.line(history_5, x='timesteps', y='entropy')
fig1.show()

(1128, 17)

,depth_count,avg_solve,max_solve,avg_timeout,min_timeout,max_timeout,ep_length
curriculum_depth,,,,,,,
1,5,0.258000,0.57,0.742000,0.43,0.91,2.532000
2,5,0.608000,0.79,0.392000,0.21,0.61,3.042000
3,10,0.791000,0.89,0.209000,0.11,0.33,3.275000
4,83,0.838434,0.96,0.161566,0.04,0.36,4.038795
5,225,0.841244,0.94,0.158756,0.06,0.30,4.766089
6,1128,0.666596,0.86,0.333404,0.14,0.58,7.985798
7,986,0.404422,0.65,0.595578,0.35,0.81,11.290030

,timesteps,policy_loss,value_loss,entropy,approx_kl,clip_fraction,loss,explained_variance,mean_episode_reward,mean_episode_length,train_solve_rate,timeout_rate,inverse_move_rate,curriculum_depth,curriculum_sampling_weights,evaluation,curriculum_evaluation
328,673792,-0.051200,0.043031,0.758996,0.026028,0.226318,-0.044864,0.618576,0.4321,8.34,0.59,0.41,0.080336,6,"{""1"":0.02,""2"":0.03,""3"":0.05,""4"":0.1,""5"":0.2,""6...",NaN,NaN
329,675840,-0.056227,0.039554,0.808321,0.029695,0.263811,-0.052616,0.570857,0.2629,9.31,0.47,0.53,0.131042,6,"{""1"":0.02,""2"":0.03,""3"":0.05,""4"":0.1,""5"":0.2,""6...",NaN,NaN
330,677888,-0.045996,0.044547,0.783726,0.022574,0.226318,-0.039397,0.630124,0.3956,8.64,0.57,0.43,0.104167,6,"{""1"":0.02,""2"":0.03,""3"":0.05,""4"":0.1,""5"":0.2,""6...",NaN,NaN
331,679936,-0.043392,0.053043,0.743365,0.021472,0.204004,-0.031738,0.610845,0.4272,8.48,0.60,0.40,0.113208,6,"{""1"":0.02,""2"":0.03,""3"":0.05,""4"":0.1,""5"":0.2,""6...",NaN,NaN
332,681984,-0.047681,0.045258,0.794587,0.026289,0.245047,-0.040944,0.617107,0.4252,8.58,0.60,0.40,0.114219,6,"{""1"":0.02,""2"":0.03,""3"":0.05,""4"":0.1,""5"":0.2,""6...","{""by_depth"":{""6"":{""action_counts"":{""B"":802,""B'...","{""advanced_curriculum"":false,""curriculum_depth..."

(2442, 17)
curriculum_depth
6    1128
7     986
5     225
4      83
3      10
1       5
2       5
Name: count, dtype: int64

In [83]:
history = pd.read_csv("../models/artifacts/ppo/depth_1_5_onehot/v005/history.csv")

history_5 = history[history['curriculum_depth'] == 5]

print(history_5.shape)
solve_rate = history.copy()

depth_stats = solve_rate.groupby('curriculum_depth').agg(
    depth_count=('curriculum_depth', 'count'),
    avg_solve=('train_solve_rate', 'mean'),
    max_solve=('train_solve_rate', 'max'),
    avg_timeout=('timeout_rate', 'mean'),
    min_timeout=('timeout_rate', 'min'),
    max_timeout=('timeout_rate', 'max'),
    ep_length=('mean_episode_length', 'mean'),
    
)

display(depth_stats)

display(history_5.head())
print(history.shape)
print(history['curriculum_depth'].value_counts())

fig1 = px.line(history_5, x='timesteps', y='train_solve_rate')
fig1.show()

(874, 17)

,depth_count,avg_solve,max_solve,avg_timeout,min_timeout,max_timeout,ep_length
curriculum_depth,,,,,,,
1,5,0.258000,0.57,0.742000,0.43,0.91,2.532000
2,5,0.608000,0.79,0.392000,0.21,0.61,3.042000
3,10,0.791000,0.89,0.209000,0.11,0.33,3.275000
4,83,0.838434,0.96,0.161566,0.04,0.36,4.038795
5,874,0.907094,1.00,0.092906,0.00,0.30,4.275915

,timesteps,policy_loss,value_loss,entropy,approx_kl,clip_fraction,loss,explained_variance,mean_episode_reward,mean_episode_length,train_solve_rate,timeout_rate,inverse_move_rate,curriculum_depth,curriculum_sampling_weights,evaluation,curriculum_evaluation
103,212992,-0.053302,0.026282,0.705782,0.025928,0.234521,-0.054276,0.637502,0.6158,5.67,0.73,0.27,0.107584,5,"{""1"":0.1,""2"":0.15,""3"":0.2,""4"":0.25,""5"":0.3}",NaN,NaN
104,215040,-0.050130,0.025584,0.689497,0.022929,0.220410,-0.051128,0.686180,0.6635,5.20,0.77,0.23,0.121154,5,"{""1"":0.1,""2"":0.15,""3"":0.2,""4"":0.25,""5"":0.3}",NaN,NaN
105,217088,-0.050726,0.024614,0.656135,0.023692,0.216553,-0.051542,0.696110,0.6404,5.16,0.75,0.25,0.127907,5,"{""1"":0.1,""2"":0.15,""3"":0.2,""4"":0.25,""5"":0.3}",NaN,NaN
106,219136,-0.049843,0.022819,0.679599,0.022493,0.206689,-0.052025,0.689116,0.6148,5.42,0.73,0.27,0.125461,5,"{""1"":0.1,""2"":0.15,""3"":0.2,""4"":0.25,""5"":0.3}",NaN,NaN
107,221184,-0.049946,0.021935,0.706741,0.022289,0.224170,-0.053113,0.734586,0.6469,5.21,0.76,0.24,0.142035,5,"{""1"":0.1,""2"":0.15,""3"":0.2,""4"":0.25,""5"":0.3}","{""by_depth"":{""5"":{""action_counts"":{""B"":687,""B'...","{""advanced_curriculum"":false,""curriculum_depth..."

(977, 17)
curriculum_depth
5    874
4     83
3     10
1      5
2      5
Name: count, dtype: int64